### ISSUE TITLE
Allow Events Handler to accept a plain privatekey instead of keyfile

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/events-handler#8]
Allow Events Handler to accept a plain privatekey instead of keyfile.

ie:  instead of using
PROVIDER_ADDRESS=''
PROVIDER_KEYFILE=''

it should accept

PROVIDER_ADDRESS='0xB229dd5cb86A316132A8dcEd54F6576f2b937cFF'
PROVIDER_PRIVATEKEY='0xc2d1c4215c0f57a4326fe3daeea8f2b244b4f81b04f18595c2c796e6b3bda82f'

**Comment by ssallam** [comment]
Implementation is completed.
