### ISSUE TITLE
Allow Events Handler to accept a  keyfile as json string

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/events-handler#9]
Allow Events Handler to accept a keyfile as json string instead of file.

ie:  instead of using
PROVIDER_ADDRESS=''
PROVIDER_KEYFILE='/some/path/to/file'

it should accept also

PROVIDER_ADDRESS='0x001ca0bb54fcc1d736ccd820f14316dedaafd772'
PROVIDER_KEYFILESTRING='{"id":"40d9999d-1934-7d4e-b57d-fd7f6c4e00a5","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"93e8f27a0c50b6da4f76a952abf57a4a"},"ciphertext":"0d77bfdae8df1201d15c7605b65469071663be8382d1fd3f2c5eeb13fbeb8d83","kdf":"pbkdf2","kdfparams":{"c":10240,"dklen":32,"prf":"hmac-sha256","salt":"3bff5646512ece63baf7dcdeeedc7f95a8b082d38927040fe8a33473c6042c49"},"mac":"47ae2eb8a767a88abb742bf7e6f36d3ce2e476dd1962e7208de05ae4c1786750"},"address":"001ca0bb54fcc1d736ccd820f14316dedaafd772","name":"","meta":"{}"}'
PROVIDER_PASSWORD='password_for_this'

**Comment by ssallam** [comment]
Development is completed, time for verification.
